# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 510b014543d6532ae3567822c073d1e6256dba65f0677d5716222b0fd96ad4dc17a13a21a969e23489a2c4d6ee4cb0929493e380ae25724bc11653f3fc7ee08f

test:
  secret_key_base: a027665ab914eb28d6ca835edc60eeac120cfc8c50392c0c3ed341a20cec2f9fcd66aee1c2b0080e10500a6f24df39a5c634504f5b77dba625a1ff00d8a2bcb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
